/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `site_statistics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_recent` tinyint(4) NOT NULL DEFAULT '0',
  `total_users` int(11) NOT NULL,
  `disabled_users` int(11) NOT NULL,
  `premium_users` int(11) NOT NULL,
  `free_delay_minutes` int(11) NOT NULL,
  `premium_delay_minutes` int(11) NOT NULL,
  `outstanding_jobs` int(11) NOT NULL,
  `external_status_job_count` int(11) NOT NULL,
  `external_status_job_errors` int(11) NOT NULL,
  `mysql_uptime` int(11) NOT NULL,
  `mysql_threads` int(11) NOT NULL,
  `mysql_questions` int(11) NOT NULL,
  `mysql_slow_queries` int(11) NOT NULL,
  `mysql_opens` int(11) NOT NULL,
  `mysql_flush_tables` int(11) NOT NULL,
  `mysql_open_tables` int(11) NOT NULL,
  `system_load_1min` float DEFAULT NULL,
  `system_load_5min` float DEFAULT NULL,
  `system_load_15min` float DEFAULT NULL,
  `users_graphs_managed_none` int(11) DEFAULT NULL,
  `users_graphs_managed_managed` int(11) DEFAULT NULL,
  `users_graphs_managed_auto` int(11) DEFAULT NULL,
  `users_graphs_need_update` int(11) DEFAULT NULL,
  `users_subscribe_announcements` int(11) DEFAULT NULL,
  `pending_subscriptions` int(11) DEFAULT NULL,
  `pending_unsubscriptions` int(11) DEFAULT NULL,
  `user_logins_after_warned` int(11) DEFAULT NULL,
  `users_login_after_warned` int(11) DEFAULT NULL,
  `user_logins_after_disabled` int(11) DEFAULT NULL,
  `users_login_after_disabled` int(11) DEFAULT NULL,
  `jobs_tests` int(11) NOT NULL DEFAULT '0',
  `jobs_timeout` int(11) NOT NULL DEFAULT '0',
  `disk_free_space` float DEFAULT NULL,
  `notifications_sent` int(11) DEFAULT NULL,
  `max_notifications_sent` int(11) DEFAULT NULL,
  `mysql_locks_immediate` int(11) DEFAULT NULL,
  `mysql_locks_blocked` int(11) DEFAULT NULL,
  `total_emails_sent` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `is_recent` (`is_recent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
