/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_admin` tinyint(4) NOT NULL DEFAULT '0',
  `is_system` tinyint(4) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `last_login` timestamp NULL DEFAULT NULL,
  `is_premium` tinyint(4) NOT NULL DEFAULT '0',
  `premium_expires` timestamp NULL DEFAULT NULL,
  `is_reminder_sent` tinyint(4) NOT NULL DEFAULT '0',
  `country` varchar(4) COLLATE utf8_unicode_ci NOT NULL,
  `user_ip` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `last_queue` timestamp NULL DEFAULT NULL,
  `referer` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_disabled` tinyint(4) NOT NULL DEFAULT '0',
  `disabled_at` timestamp NULL DEFAULT NULL,
  `disable_warned_at` timestamp NULL DEFAULT NULL,
  `is_disable_warned` tinyint(4) NOT NULL DEFAULT '0',
  `graph_managed_type` varchar(16) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'none',
  `preferred_crypto` varchar(3) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'btc',
  `preferred_fiat` varchar(3) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'usd',
  `needs_managed_update` tinyint(4) NOT NULL DEFAULT '0',
  `last_managed_update` timestamp NULL DEFAULT NULL,
  `subscribe_announcements` tinyint(4) NOT NULL DEFAULT '0',
  `last_report_queue` timestamp NULL DEFAULT NULL,
  `is_first_report_sent` tinyint(4) NOT NULL DEFAULT '0',
  `logins_after_disable_warned` tinyint(4) NOT NULL DEFAULT '0',
  `logins_after_disabled` tinyint(4) NOT NULL DEFAULT '0',
  `first_report_sent` timestamp NULL DEFAULT NULL,
  `reminder_sent` timestamp NULL DEFAULT NULL,
  `securities_count` int(11) NOT NULL DEFAULT '0',
  `securities_last_count_queue` timestamp NULL DEFAULT NULL,
  `disable_graph_refresh` tinyint(4) NOT NULL DEFAULT '0',
  `notifications_sent` int(11) NOT NULL DEFAULT '0',
  `last_summaries_update` datetime DEFAULT NULL,
  `locale` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL,
  `password_hash` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `password_last_changed` datetime DEFAULT NULL,
  `last_password_reset` datetime DEFAULT NULL,
  `last_tx_creator_queue` timestamp NULL DEFAULT NULL,
  `last_account_change` timestamp NULL DEFAULT NULL,
  `last_sum_job` timestamp NULL DEFAULT NULL,
  `has_added_account` tinyint(4) NOT NULL DEFAULT '0',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0',
  `requested_delete_at` timestamp NULL DEFAULT NULL,
  `emails_sent` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `is_premium` (`is_premium`),
  KEY `is_admin` (`is_admin`),
  KEY `is_system` (`is_system`),
  KEY `is_disabled` (`is_disabled`),
  KEY `graph_managed_type` (`graph_managed_type`),
  KEY `is_first_report_sent` (`is_first_report_sent`),
  KEY `locale` (`locale`),
  KEY `password_hash` (`password_hash`),
  KEY `has_added_account` (`has_added_account`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `users` (`id`, `name`, `email`, `is_admin`, `is_system`, `created_at`, `updated_at`, `last_login`, `is_premium`, `premium_expires`, `is_reminder_sent`, `country`, `user_ip`, `last_queue`, `referer`, `is_disabled`, `disabled_at`, `disable_warned_at`, `is_disable_warned`, `graph_managed_type`, `preferred_crypto`, `preferred_fiat`, `needs_managed_update`, `last_managed_update`, `subscribe_announcements`, `last_report_queue`, `is_first_report_sent`, `logins_after_disable_warned`, `logins_after_disabled`, `first_report_sent`, `reminder_sent`, `securities_count`, `securities_last_count_queue`, `disable_graph_refresh`, `notifications_sent`, `last_summaries_update`, `locale`, `password_hash`, `password_last_changed`, `last_password_reset`, `last_tx_creator_queue`, `last_account_change`, `last_sum_job`, `has_added_account`, `is_deleted`, `requested_delete_at`, `emails_sent`) VALUES (100,'System','support@openclerk.org',0,1,'2015-02-20 02:42:13',NULL,'2015-02-20 02:42:15',0,NULL,0,'','',NULL,NULL,0,NULL,NULL,0,'none','btc','usd',0,NULL,0,NULL,0,0,0,NULL,NULL,0,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,0);
